kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: johnbreth/netauto
  commands:
  - black . --check

- name: Batfish Prechecks
  image: johnbreth/netauto
  commands:
  - python batfishcheck.py

- name: Precheck Configuration Diff
  image: johnbreth/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - python build.py --dry_run

- name: Deploy Configuration
  image: johnbreth/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - python build.py --no_dry_run
  when:
    branch:
    - master
    - main

- name: Check IP Interfaces
  image: johnbreth/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
#  - pip3 install -r requirements.txt
  - python3 bat.py

- name: Suzieq Check
  image: johnbreth/suzieq
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
  - pip install suzieq rich
  - python test_suzieq.py
  when:
    branch:
    - master
    - main
  volumes:
  - name: suzieq
    path: /tmp/suz
volumes:
- name: suzieq
  host:
    path: /home/jb/Docker/suz
#trigger:
# branch:
#    exclude:
#   - main
#   - master