kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: johnbreth/netauto
  commands:
  - black . --check

- name: Batfish Prechecks
  image: johnbreth/netauto
  commands:
  - python test.py

- name: Install and Deploy
  image: johnbreth/netauto
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USER:
      from_secret: USER
  commands:
#  - pip3 install -r requirements.txt
  - python3 bat.py

#trigger:
#  branch:
#    exclude:
#    - main
#    - master