---
- hosts: routers
  become: yes

  tasks:
    - name: Create Loopback888
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback888
            description: Created for David!
            enabled: true


    - name: Add IP address to L888
      cisco.ios.ios_l3_interface:
        name: Loopback888
        ipv4: 192.168.255.88/32
