---
datacenter:
  children:
    routers:
      hosts:
        10.30.10.8[1:3]:
      vars:
        testVar: 999
    switches:
      hosts:
        10.30.10.241:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_ssh_pass: dikstra
    ansible_become_password: dikstra
    ntp_servers:
      - 10.30.11.10
      - 10.20.11.10